"""Initial schema setup

Revision ID: dca72fdb4d78
Revises: 
Create Date: 2026-02-23 14:45:34.529733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca72fdb4d78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_configs',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('welcome_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('role_select_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('stream_updates_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('video_updates_channel_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('stream_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('vod_url', sa.String(), nullable=True),
    sa.Column('peak_viewers', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stream_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('vod_timestamp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['stream_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stream_events')
    op.drop_table('stream_sessions')
    op.drop_table('guild_configs')
    # ### end Alembic commands ###
